version: '3.8'

services:
  pos-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://pos_user:pos_12345@postgres:5432/pos_db

  postgres:
    image: postgres:latest
    ports:
      - '5433:5432'
      # - '5432:5432'
    environment:
      POSTGRES_DB: pos_db
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_12345
# # version: '3.8'

# # services:
# #   postgres_db:
# #     image: postgres:14
# #     container_name: postgres_db
# #     restart: always
# #     ports:
# #       - '5432:5432'
# #     environment:
# #       POSTGRES_USER: pos_user
# #       POSTGRES_PASSWORD: pos_12345
# #       POSTGRES_DB: pos_db
# #     volumes:
# #       - pg_data:/var/lib/postgresql/data

# #   server:
# #     container_name: express_server
# #     build:
# #       context: .
# #       dockerfile: Dockerfile
# #     ports:
# #       - '3000:3000'
# #     depends_on:
# #       - postgres_db
# #     env_file:
# #       - .env.prod
# #     command: yarn run dev

# #   prisma-studio:
# #     container_name: prisma_studio
# #     image: node:20
# #     working_dir: /app
# #     volumes:
# #       - .:/app
# #     depends_on:
# #       - postgres_db
# #     env_file:
# #       - .env.prod
# #     ports:
# #       - '5555:5555'
# #     command: >
# #       sh -c "yarn install && npx prisma generate && npx prisma studio --port 5555"

# # volumes:
# #   pg_data:
# version: '3.7'

# services:
#   postgres:
#     image: postgres:15
#     restart: always
#     environment:
#       - POSTGRES_DB: pos_db
#       - POSTGRES_USER: pos_user
#       - POSTGRES_PASSWORD: pos_12345
#     ports:
#       - '5432:5432'
#     networks:
#       - prisma-network
#     healthcheck:
#       test: ['CMD-SHELL', 'pg_isready -U prisma -d postgres']
#       interval: 5s
#       timeout: 2s
#       retries: 20
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     command: postgres -c listen_addresses='*'
#     logging:
#       options:
#         max-size: '10m'
#         max-file: '3'

# networks:
#   prisma-network:

# volumes:
#   postgres_data:
# # version: '3.8'

# # services:
# #   pos-server:
# #     build:
# #       context: .
# #       dockerfile: Dockerfile
# #     ports:
# #       - '3000:3000'
# #     depends_on:
# #       - postgres
# #     environment:
# #       - DATABASE_URL=postgresql://pos_user:pos_12345@postgres:5432/pos_db

# #   postgres:
# #     image: postgres:latest
# #     ports:
# #       # - '5433:5432'
# #       - '5432:5432'
# #     environment:
# #       POSTGRES_DB: pos_db
# #       POSTGRES_USER: pos_user
# #       POSTGRES_PASSWORD: pos_12345
