export enum ENUM_USER_ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  MARKETING_MANAGER = 'MARKETING_MANAGER',
  USER = 'USER',
  MODERATOR = 'MODERATOR',
}

export enum ENUM_USER_PASSWORD {
  DEFAULT_USER_PASSWORD = 'user12345',
}
